---
language: ruby
rvm:
  - 2.1.3
  - 1.9.3-p547
before_script: "if [[ $TRAVIS_RUBY_VERSION != '1.9.3-p547' || $TRAVIS_SECURE_ENV_VARS != 'true' ]]; then unset CODECLIMATE_REPO_TOKEN; fi"
install: bundle install --deployment --without debug
notifications:
  webhooks:
    urls:
      - http://build-monitor.cfapps.io/projects/WLBP/webhook
    on_start: true
env:
  global:
    secure: njB2370t9TXXmvtVBB7z/aodGOI13sfeCB+Eh/Y/9oSmlnrOHav5QXJbdHKgYbQ+YhBdNfPF9KjW/+bNwi0NbGii0eiTMXw1y+3FDVfTWFFYJYdgpHVMQbZrjVET7DdRPzOmF7xdKz7KK6MhUzWIgA0o000291akDfkWSA5ZlwE= # CODECLIMATE_REPO_TOKEN
    secure: prq0sJy81ZMZf/AKMLyLRcv9AoZDbwRZIwrBNL2xa2+rd9nZVfB4Y5wWWP9bnzyw2oq63RMu76cw65QUL7gJLmPrGk+qQBNIBwP8Ny/jH3A81KLFaBpA6SzBulg9OEVHcWPaFpB+Ux+ls2+dn+HAbUmBdOca/PiHHBDJ52uC6Sc= # ORACLE_JRE_DOWNLOAD
    secure: XscRbtw8N/Q7tl0XoLF2r1QvclIFjNz4WbLssJsCgID6apKcr/iPtaz28+Of2KZf2MDEodM6lwVAyq5FlbbHbAelyno7mvvQ0XSy63/8mY1LWxv+mE6b9GIzDrIlBfEX1Qwy7nHkq2oi+MH5gjE2vW3SNM4b3pXf6bSaCGiQH3g= # WEBLOGIC_DOWNLOAD
